name: frame_field
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - absl-py=0.9.0=py38_0
  - affine=2.3.0=py_0
  - argon2-cffi=20.1.0=py38h7b6447c_1
  - asn1crypto=1.3.0=py38_0
  - async_generator=1.10=py_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py38_0
  - blas=2.14=openblas
  - bleach=3.2.1=py_0
  - blinker=1.4=py38_0
  - boost-cpp=1.72.0=h8e57a91_0
  - bravado=10.5.0=py_0
  - bravado-core=5.16.0=py_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.10.14=0
  - cachetools=3.1.1=py_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.6.20=py38_0
  - cffi=1.14.0=py38h2e261b9_0
  - cfitsio=3.470=hb7c8383_2
  - chardet=3.0.4=py38_1003
  - click=7.1.1=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.5.0=py38_0
  - cloudpickle=1.4.0=py_0
  - cryptography=2.8=py38h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - curl=7.69.1=hbc83047_0
  - cycler=0.10.0=py38_0
  - cytoolz=0.10.1=py38h7b6447c_0
  - dask-core=2.15.0=py_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - dill=0.3.1.1=py38_0
  - entrypoints=0.3=py38_0
  - et_xmlfile=1.0.1=py38_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.1.3=h167e202_0
  - fiona=1.8.13=py38h900e953_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.9.1=h8a8886c_1
  - freexl=1.0.5=h14c3975_0
  - future=0.18.2=py38_0
  - gdal=3.0.4=py38hbb6b9fb_0
  - geojson=2.5.0=py_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.5.1=h38872f0_8
  - giflib=5.2.1=h516909a_2
  - gitdb=4.0.2=py_0
  - gitpython=3.1.1=py_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gnutls=3.6.5=h71b1129_1002
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.27.2=py38hf8bcb03_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - imagecodecs-lite=2019.12.3=py38h1e0a361_0
  - imageio=2.8.0=py_0
  - importlib_metadata=1.5.0=py38_0
  - imutils=0.5.3=py38_1
  - intel-openmp=2020.0=166
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_1
  - jasper=1.900.1=hd497a04_4
  - jdcal=1.4.1=py_0
  - jedi=0.17.0=py38_0
  - jinja2=2.11.2=py_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - jsmin=2.2.2=py38_1000
  - json-c=0.13.1=h1bed415_0
  - jsonref=0.2=py_0
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.2=py_0
  - kealib=1.4.13=hec59c27_0
  - kiwisolver=1.2.0=py38hfd86e86_0
  - krb5=1.17.1=h173b8e3_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.69.1=h20c2e04_0
  - libdap4=3.20.4=hd3bb157_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=3.0.4=h20022a4_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h63c8f33_5
  - libkml=1.3.0=hb574062_1011
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libnetcdf=4.7.3=nompi_h9f9fd6a_101
  - libopenblas=0.3.7=h5ec1e0e_6
  - libopencv=4.2.0=py38_2
  - libpng=1.6.37=hbc83047_0
  - libpq=12.2=h20c2e04_0
  - libprotobuf=3.11.4=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialite=4.3.0a=ha48a99a_1034
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h1bed415_1
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvmlite=0.31.0=py38hd408876_0
  - lz4-c=1.8.3=he1b5a44_1001
  - markdown=3.1.1=py38_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py38h2af1d28_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.0=166
  - monotonic=1.5=py_0
  - msgpack-python=1.0.0=py38hfd86e86_1
  - multiprocess=0.70.9=py38h1e0a361_1
  - munch=2.5.0=py_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - neptune-client=0.4.107=py_0
  - nest-asyncio=1.4.1=py_0
  - nettle=3.4.1=hbb512f6_0
  - networkx=2.4=py_0
  - ninja=1.9.0=py38hfd86e86_0
  - nose=1.3.7=py38_2
  - notebook=6.1.4=py38_0
  - nspr=4.22=he6710b0_0
  - nss=3.46.1=hab99668_0
  - numba=0.48.0=py38h0573a6f_0
  - numpy-base=1.18.1=py38h2f8d375_1
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - opencv=4.2.0=py38_2
  - openh264=1.8.0=hd408876_0
  - openjpeg=2.3.1=h981e76c_3
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1h=h7b6447c_0
  - overpy=0.4=py_0
  - pandas=1.0.3=py38h0573a6f_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.1.2=py38hb39fc2d_0
  - pip=20.0.2=py38_1
  - pixman=0.38.0=h7b6447c_0
  - plyfile=0.7.2=pyh9f0ad1d_0
  - poppler=0.67.0=h14e79db_8
  - poppler-data=0.4.9=0
  - postgresql=12.2=h20c2e04_0
  - proj=6.3.0=hc80f0dc_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - protobuf=3.11.4=py38he6710b0_0
  - ptyprocess=0.6.0=py38_0
  - py-opencv=4.2.0=py38h5ca1d4c_2
  - py3nvml=0.2.5=py38h32f6830_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=19.1.0=py38_0
  - pyparsing=2.4.7=py_0
  - pyproj=2.5.0=py38h8ff28aa_0
  - pyqt=5.12.3=py38hcca6a23_1
  - pyrsistent=0.16.0=py38h7b6447c_0
  - pysocks=1.7.1=py38_0
  - python=3.8.2=hcf32534_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.4.0=py3.8_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py38h7b6447c_0
  - pyyaml=5.3.1=py38h7b6447c_0
  - pyzmq=19.0.2=py38he6710b0_1
  - qt=5.12.5=hd8c4c69_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - rasterio=1.1.3=py38h900e953_0
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py38_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scikit-image=0.16.2=py38h0573a6f_0
  - scikit-learn=0.22.1=py38h22eb022_0
  - scipy=1.4.1=py38habc2bb6_0
  - send2trash=1.5.0=py38_0
  - simplejson=3.17.0=py38h7b6447c_0
  - six=1.14.0=py38_0
  - skan=0.8=py_0
  - sknw=0.13=py_1
  - smmap=3.0.2=py_0
  - snuggs=1.4.7=py_0
  - sqlite=3.31.1=h62c20be_1
  - swagger-spec-validator=2.5.0=py_0
  - tbb=2018.0.5=h6bb024c_0
  - tensorboard=2.1.0=py3_0
  - terminado=0.9.1=py38_0
  - testpath=0.4.4=py_0
  - tifffile=2020.5.7=py_0
  - tiledb=1.7.0=hcde45ca_2
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - torchvision=0.5.0=py38_cu101
  - tornado=6.0.4=py38h7b6447c_1
  - tqdm=4.43.0=py_0
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.8=py38_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py38_1
  - websocket-client=0.57.0=py38_1
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - x264=1!152.20180806=h7b6447c_0
  - xerces-c=3.2.2=h8412b87_1004
  - xlrd=1.2.0=py_0
  - xmltodict=0.12.0=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h3b9ef0a_2
  - pip:
    - calmsize==0.1.3
    - coverage==5.1
    - cython==0.29.17
    - descartes==1.0.1
    - gym==0.17.1
    - imagecodecs==2020.2.18
    - kornia==0.1.2+7bcb521
    - more-itertools==8.2.0
    - numpy==1.18.3
    - packaging==20.3
    - pluggy==0.13.1
    - py==1.8.1
    - pycocotools==2.0
    - pyglet==1.5.0
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pytest==5.4.1
    - pytest-cov==2.8.1
    - pytorch-memlab==0.1.0
    - setuptools==46.1.3
    - torch-scatter==2.0.4
prefix: /home/lydorn/anaconda3/envs/frame_field

